server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chefpro
    username: chefpro_user
    password: chefPro01;

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
