server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chefpro
    username: root
    password: TU_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update   # para desarrollo; en producci√≥n mejor 'validate' o scripts SQL
    show-sql: true
