server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET:ChefPr0$uperS3cretK3y!2025@SecureHS256}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/chef_pro}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:chefpr01;}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:never}

logging:
  level:
    org.hibernate.SQL: ${LOG_LEVEL_SQL:DEBUG}
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_BIND:TRACE}
